### ISSUE TITLE
Flipping orientation, then dismissing vc causes strange sizing issues

### ISSUE THREAD

**Issue by liquidg3** [joelconnects/FlipTheBlinds#1]
Here is a video of it in action: https://www.dropbox.com/s/l96bjv49s522erd/rotation%20issues.mp4?dl=0

If I comment out:

    func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? { 
        return FTBAnimationController(displayType: .dismiss, direction: .down, speed: .moderate)
      }

It works perfectly, but the segue animation is mega lame!

**Comment by joelconnects** [comment]
Thank you for the feedback. The code currently does not account for changes in orientation. As mentioned in the readme, it is designed and intended for portrait orientation only. 

I will consider adding orientation detection and related enhancements to future releases. Thanks.
